server: 
  port: 9004
spring: 
  application:  
    name: ts-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ts_article
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ts_comment
