server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ts_base
    data-username: root
    data-password: root
  jpa:
    database: mysql
    show-sql: true



